### ISSUE TITLE
theano.In() error

### ISSUE THREAD

**Issue by nenduru1** [craffel/theano-tutorial#8]
hi 
I tried to run this code but i am getting error,can you look into this issue?

linear_mix = theano.function([A, x, theano.In(b, default=b_default)], [y, z])
TypeError: __init__() got an unexpected keyword argument 'default'

**Comment by craffel** [comment]
Looks like this was broken in 5e3fa7f.  Just pushed a fix in 777b2ca.
